### PR TITLE
tf2.8.0 and py3.10 support

### PR DESCRIPTION
**Pull request by scarrazza**
Adding tf2.8.0 and py3.10 support.
Before merging this PR we should release the current main so there is a version for tf2.7.0.

### CODE REVIEW

**Review by stavros11 — APPROVED** [review]
Thanks, looks good to me. I tested in an environment with Python 3.10 and tf2.8 and both qibo and qibotf tests pass.

**Comment by andrea-pasquale** [comment]
When I try to run tests on my laptop pytest crashes for some reason.
The crash happens also with the main branch of qibotf so I think that this PR is fine.
I perform the following commands on a clean conda environment:
```
conda create -n test_qibotf python=3.10
conda activate test_qibotf
python -m pip install --upgrade pip
pip install qibo --pre
pip install -r requirements.txt
pip install .
pip install --upgrade pytest-cov
pip install --upgrade pylint
```
The when I try to run tests the terminal aborts the execution.
Any ideas on why this happens?

**Comment by stavros11** [comment]
> The when I try to run tests the terminal aborts the execution.
> 
> Any ideas on why this happens?

Do you get a particular error or just aborted? Can you check if you have the compiled custom operators (some .o files). I usually use python setup.py build to compile the operators after installing qibotf. I'm not sure if this step is required when you install from source with pip install .

**Comment by andrea-pasquale** [comment]
> Do you get a particular error or just aborted? 

Just abort.
```
platform darwin -- Python 3.10.0, pytest-7.0.0, pluggy-1.0.0
rootdir:
plugins: cov-3.0.0
collecting ... [1]    54572 abort      pytest --cov=qibotf --cov-report=xml --pyargs qibotf
```

> Can you check if you have the compiled custom operators (some .o files). I usually use python setup.py build to compile the operators after installing qibotf. I'm not sure if this step is required when you install from source with pip install .

Yes, I have the compiled custom operators. I've try rerunning with python setup.py build but I still get the abort.

**Review by andrea-pasquale — APPROVED** [review]

**Comment by andrea-pasquale** [comment]
> @stavros11 just a quick feedback, I have checked with Andrea, there is no problem in the code. The issue was pip was not recompiling the code between different anaconda environments, so there are missing links. Usually this issue is quite simple to debug on linux, however on his mac it raises an abort...

Exactly we can blame my mac on this one.

**Comment by stavros11** [comment]
> @stavros11 just a quick feedback, I have checked with Andrea, there is no problem in the code. The issue was pip not recompiling the code between different anaconda environments, so there are missing links. Usually this issue is quite simple to debug on linux, however on his mac it raises an abort...

Regarding this, when I install with `pip install -e .` (or `python setup.py develop`) on different environments and then I switch environment I always recompile without re-installing using `python setup.py build`. In fact I have a bash script which removes the compiled binaries (`*.o`, `*.cudao`) and recompiles. I am not sure if this is the proper way of doing things though.

**Comment by scarrazza** [comment]
Indeed, let me open a PR fixing Andrea's issue by forcing a `make clean` before installing/compiling.

**Pull request merged**
