### PR TITLE
upgrade to tensorflow 2.6.0

### PR DESCRIPTION
**Pull request by scarrazza**
Upgrading tensorflow to v2.6.0.

### CODE REVIEW

**Comment by scarrazza** [comment]
@stavros11 I think this PR can be merge asap, let me know if you agree. This might help with the numpy issue reported in https://github.com/qiboteam/qibo/pull/453

**Review by stavros11 — APPROVED** [review]
Thanks for the update, yes sure we can merge.

**Comment by scarrazza** [comment]
@stavros11, thanks. I am planning to make a new release now, do you agree (or are you planning to add some extra feature)?

**Comment by stavros11** [comment]
> @stavros11, thanks. I am planning to make a new release now, do you agree (or are you planning to add some extra feature)?

Releasing is okay for me. I do not have any plan for new features in qibotf for the time being.

**Comment by scarrazza** [comment]
Thanks.

**Pull request merged**
