### PR TITLE
Add `TensorflowCustomBackend` class from qibo

### PR DESCRIPTION
**Pull request by stavros11**
Following qiboteam/qibo#500 this adds the `TensorflowCustomBackend` that was previously in qibo here. Since this class inherits the AbstractBackend from qibo, qibo is now added in the requirements list for qibotf.

@scarrazza I tried removing the requirements.txt similarly to what you did for qibo and qibojit but there seems to be an issue here. Is there another reason this file is required here? If yes, I will put it back and just add the qibo requirement there.

### CODE REVIEW

**Comment by stavros11** [comment]
I added some tests for `TensorflowCustomBackend` to get the coverage back to 100%. Similarly to qiboteam/qibojit#35 here I am installing qibo from source until the new backend independent version is released. I also had to disable Python 3.6.

@scarrazza, do you have any idea why pylint is failing [here](https://github.com/qiboteam/qibotf/runs/4094521430?check_suite_focus=true)?

**Comment by scarrazza** [comment]
> @scarrazza, do you have any idea why pylint is failing here?

Should be the incompatibility you have fixed here: https://github.com/qiboteam/qibotf/pull/12/commits/024c1657e115938a06b6eb37a6eee03c417d7700

**Comment by stavros11** [comment]
> Should be the incompatibility you have fixed here: [024c165](https://github.com/qiboteam/qibotf/commit/024c1657e115938a06b6eb37a6eee03c417d7700)

I am giving this another try but I believe this results to some other installation issues.

**Comment by scarrazza** [comment]
> I am giving this another try but I believe this results to some other installation issues.

@stavros11 just fixed now.

**Comment by stavros11** [comment]
> @stavros11 just fixed now.

Thanks for the fix. This should be good to go, we just need to remember to reset the CI to `pip install qibo --pre` and re-enable Python 3.6 once qibo is released.

**Comment by scarrazza** [comment]
@stavros11 thanks, I am looking into py36 right now. The major issue we have is that some qibo dependency is asking for matplotlib 3.4 which is not compatible with py36, I am not sure which package is forcing that version, however if we can get rid or disable this requirement for qibo then we can retry this PR with an updated version of the backendcls branch.

**Comment by stavros11** [comment]
> @stavros11 thanks, I am looking into py36 right now. The major issue we have is that some qibo dependency is asking for matplotlib 3.4 which is not compatible with py36, I am not sure which package is forcing that version, however if we can get rid or disable this requirement for qibo then we can retry this PR with an updated version of the backendcls branch.

I believe the py36 issue disappears if I install qibo using `pip install .` like you do here instead of `python setup.py build`. I just pushed this in qiboteam/qibojit#35 and I think CI passes.

**Comment by scarrazza** [comment]
Ok, I will have another look, the problem was raised from https://github.com/qiboteam/qibotf/runs/4092821511?check_suite_focus=true#step:5:235.

On the other hand looks like keras-2.7.0 is breaking the actions for qibo https://github.com/qiboteam/qibo/actions/runs/1421436395. If pinning down to 2.6.0 works then we will have to include this requirement here.

**Review by scarrazza — APPROVED** [review]

**Pull request merged**
